In [1]:
import numpy as np

In [2]:
"""
Computing reciprocals in loops
"""

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(values)

compute_reciprocals(values)

[7 5 9 1 6]


array([0.14285714, 0.2       , 0.11111111, 1.        , 0.16666667])

In [3]:
"""
comparison: loop vs ufuncs(vectorized)
"""

big_array = np.random.randint(1, 100, size=100000)

%timeit compute_reciprocals(big_array)

193 ms ± 9.01 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit 1 / big_array

119 µs ± 6.63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
"""
numpy.unfunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=(5))
arr2 = np.random.randint(10, size=(5))
print(arr1, arr2)

arr1 = arr2 - 2
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4**2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[-2 -1  5  4  7]
[-2  0 12 10 16]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [8]:
"""
UFunc: Array Arithmetic
"""
x = np.arange(4)
print("x    =",x)
print("x + 5 =",x + 5)


x    = [0 1 2 3]
x + 5 = [5 6 7 8]


In [9]:
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [11]:
theta = np.linspace(0, np.pi, 3)

print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [14]:
x = np.arange(1,5)
print(x)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [16]:
x = np.arange(1, 15)
print(x)

accum = np.add.accumulate(x)
print(accum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]


In [20]:
np.random.seed(2)
arr = np.random.rand(1000000)

print(arr)
print('sum =', np.sum(arr))

%timeit sum(arr)

[0.4359949  0.02592623 0.54966248 ... 0.78483191 0.00778062 0.42442656]
sum = 499468.5166853333
82.7 ms ± 11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
